// <auto-generated />
using System;
using Bancos.Mcp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bancos.Mcp.Migrations
{
    [DbContext(typeof(McpCatalogDbContext))]
    [Migration("20260721054505_InitialMcpCatalog")]
    partial class InitialMcpCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bancos.Mcp.Domain.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBanks")
                        .HasComment("Identificador único del banco.");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("code")
                        .HasComment("Código corto que identifica al banco.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("createdAt")
                        .HasComment("Fecha y hora de creación del registro.");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("isEnabled")
                        .HasComment("Indica si el banco puede usarse en el catálogo.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name")
                        .HasComment("Nombre comercial o legal del banco.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updatedAt")
                        .HasComment("Fecha y hora de la última actualización del registro.");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tbBanks", null, t =>
                        {
                            t.HasComment("Catálogo de entidades bancarias disponibles para cuentas y tipos de cambio.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Code = "BCR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Banco de Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "BN",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Banco Nacional de Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "BAC",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "BAC Credomatic"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Code = "COOPEALIANZA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Coopealianza"
                        });
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBankAccounts")
                        .HasComment("Identificador único de la cuenta bancaria.");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("accountType")
                        .HasComment("Tipo de producto financiero: tarjeta de crédito, débito o préstamo.");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBanks")
                        .HasComment("Identificador del banco propietario de la cuenta.");

                    b.Property<string>("CardFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .HasColumnName("cardFingerprint")
                        .IsFixedLength()
                        .HasComment("Huella criptográfica opcional de la tarjeta asociada.");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("code")
                        .HasComment("Código interno no sensible que identifica la cuenta.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("createdAt")
                        .HasComment("Fecha y hora de creación del registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("currencyCode")
                        .IsFixedLength()
                        .HasComment("Código de moneda permitido para la cuenta.");

                    b.Property<string>("IdentifierHash")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .HasColumnName("identifierHash")
                        .IsFixedLength()
                        .HasComment("Huella criptográfica opcional del identificador bancario normalizado.");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("isEnabled")
                        .HasComment("Indica si la cuenta puede usarse en el catálogo.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updatedAt")
                        .HasComment("Fecha y hora de la última actualización del registro.");

                    b.HasKey("Id");

                    b.HasIndex("IdentifierHash")
                        .IsUnique()
                        .HasFilter("[identifierHash] IS NOT NULL");

                    b.HasIndex("BankId", "Code")
                        .IsUnique();

                    b.ToTable("tbBankAccounts", null, t =>
                        {
                            t.HasComment("Catálogo de cuentas, tarjetas y préstamos asociados a un banco.");

                            t.HasCheckConstraint("CK_tbBankAccounts_accountType", "[accountType] IN ('credit-card', 'debit-card', 'loan')");

                            t.HasCheckConstraint("CK_tbBankAccounts_currencyCode", "[currencyCode] IN ('CRC', 'USD')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "bac-credit-01-crc",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "CRC",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "bac-credit-01-usd",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "USD",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "bac-credit-02-crc",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "CRC",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "bac-credit-02-usd",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "USD",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "bac-credit-03-crc",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "CRC",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "bac-credit-03-usd",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "USD",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "bac-credit-04-crc",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "CRC",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "bac-credit-04-usd",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "USD",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000009"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "bn-credit-01-crc",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "CRC",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000010"),
                            AccountType = "credit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "bn-credit-01-usd",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "USD",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000011"),
                            AccountType = "debit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "bn-debit-01-usd",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "USD",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000012"),
                            AccountType = "debit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Code = "bcr-debit-01-crc",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "CRC",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000013"),
                            AccountType = "debit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "bac-debit-01-crc",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "CRC",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000014"),
                            AccountType = "debit-card",
                            BankId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "bn-debit-01-crc",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "CRC",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000015"),
                            AccountType = "loan",
                            BankId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Code = "coopealianza-loan-01-crc",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "CRC",
                            IsEnabled = true
                        });
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.BankAccountImportTemplate", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBankAccounts")
                        .HasComment("Identificador de la cuenta bancaria compatible con la plantilla.");

                    b.Property<Guid>("ImportTemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idImportTemplates")
                        .HasComment("Identificador de la plantilla compatible con la cuenta.");

                    b.HasKey("BankAccountId", "ImportTemplateId");

                    b.HasIndex("ImportTemplateId");

                    b.ToTable("tbBankAccountImportTemplates", null, t =>
                        {
                            t.HasComment("Relación entre cuentas bancarias y formatos de importación admitidos.");
                        });

                    b.HasData(
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000012"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000012"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000001"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000001"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000001"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000001"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000003"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000003"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000003"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000003"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000004"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000004"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000004"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000004"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000005"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000005"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000005"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000005"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000006"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000006"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000006"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000006"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000007"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000007"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000007"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000007"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000008"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000008"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000008"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000008"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000009"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000010"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000011"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000014"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000013"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            BankAccountId = new Guid("40000000-0000-0000-0000-000000000015"),
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idExchangeRates")
                        .HasComment("Identificador único del tipo de cambio.");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBanks")
                        .HasComment("Identificador del banco que publica el tipo de cambio.");

                    b.Property<decimal>("CrcPerUnit")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("crcPerUnit")
                        .HasComment("Cantidad de colones costarricenses equivalente a una unidad de moneda.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("createdAt")
                        .HasComment("Fecha y hora de creación del registro.");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("currencyCode")
                        .IsFixedLength()
                        .HasComment("Moneda cotizada; actualmente solo se permite USD.");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rateDate")
                        .HasComment("Fecha de vigencia del tipo de cambio.");

                    b.HasKey("Id");

                    b.HasIndex("BankId", "RateDate", "CurrencyCode")
                        .IsUnique();

                    b.ToTable("tbExchangeRates", null, t =>
                        {
                            t.HasComment("Tipos de cambio de USD expresados en colones costarricenses por banco y fecha.");

                            t.HasCheckConstraint("CK_tbExchangeRates_crcPerUnit", "[crcPerUnit] > 0");

                            t.HasCheckConstraint("CK_tbExchangeRates_currencyCode", "[currencyCode] = 'USD'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            BankId = new Guid("30000000-0000-0000-0000-000000000002"),
                            CrcPerUnit = 458m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "USD",
                            RateDate = new DateOnly(2026, 7, 20)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            BankId = new Guid("30000000-0000-0000-0000-000000000003"),
                            CrcPerUnit = 458m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            CurrencyCode = "USD",
                            RateDate = new DateOnly(2026, 7, 20)
                        });
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.ImportTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idImportTemplates")
                        .HasComment("Identificador único de la plantilla de importación.");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("code")
                        .HasComment("Código estable que identifica la plantilla.");

                    b.Property<string>("ContentKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("contentKind")
                        .HasComment("Tipo de contenido esperado en el archivo.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("createdAt")
                        .HasComment("Fecha y hora de creación del registro.");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("isEnabled")
                        .HasComment("Indica si la plantilla puede utilizarse para detectar archivos.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name")
                        .HasComment("Nombre descriptivo de la plantilla de importación.");

                    b.Property<string>("ParserKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("parserKey")
                        .HasComment("Clave del analizador que procesa el formato.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updatedAt")
                        .HasComment("Fecha y hora de la última actualización del registro.");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tbImportTemplates", null, t =>
                        {
                            t.HasComment("Catálogo de formatos de archivos de importación reconocidos.");

                            t.HasCheckConstraint("CK_tbImportTemplates_contentKind", "[contentKind] IN ('csv', 'html', 'xls', 'pdf')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "bcr-debit-csv-v1",
                            ContentKind = "csv",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Movimientos de cuenta BCR",
                            ParserKey = "bcr-debit-csv"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "bac-credit-csv-v1",
                            ContentKind = "csv",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Resumen de tarjeta BAC",
                            ParserKey = "bac-credit-csv"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "bcr-debit-html-xls-v1",
                            ContentKind = "html",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Movimientos BCR HTML",
                            ParserKey = "bcr-debit-html"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "bank-account-movements-xls-v1",
                            ContentKind = "xls",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Movimientos de cuenta XLS",
                            ParserKey = "bank-account-movements-xls"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "bac-credit-financing-xls-v1",
                            ContentKind = "xls",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Financiamientos BAC",
                            ParserKey = "bac-credit-financing-xls"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Code = "bac-credit-online-pdf-v1",
                            ContentKind = "pdf",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Tarjeta BAC en linea",
                            ParserKey = "bac-credit-online-pdf"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Code = "coopealianza-loan-pdf-v1",
                            ContentKind = "pdf",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Prestamo Coopealianza",
                            ParserKey = "coopealianza-loan-pdf"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Code = "bac-account-statement-pdf-v1",
                            ContentKind = "pdf",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Estado de cuenta consolidado BAC",
                            ParserKey = "bac-account-statement-pdf"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Code = "bn-card-statement-pdf-v1",
                            ContentKind = "pdf",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Estado de cuenta de tarjeta Banco Nacional",
                            ParserKey = "bn-card-statement-pdf"
                        });
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.ImportTemplatePattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idImportTemplatePatterns")
                        .HasComment("Identificador único del patrón de detección.");

                    b.Property<string>("AlternativeTermGroupsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alternativeTermGroupsJson")
                        .HasComment("Grupos de términos alternativos aceptados por el patrón.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("createdAt")
                        .HasComment("Fecha y hora de creación del registro.");

                    b.Property<short>("DetectorVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("detectorVersion")
                        .HasComment("Versión del algoritmo de detección asociado.");

                    b.Property<Guid>("ImportTemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idImportTemplates")
                        .HasComment("Identificador de la plantilla asociada al patrón.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive")
                        .HasComment("Indica si el patrón está habilitado para detectar archivos.");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("isApproved")
                        .HasComment("Indica si el patrón fue aprobado para uso productivo.");

                    b.Property<string>("PatternKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("patternKind")
                        .HasComment("Tipo de patrón usado para la detección.");

                    b.Property<string>("RequiredTermsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requiredTermsJson")
                        .HasComment("Términos que deben existir en el contenido para aceptar el patrón.");

                    b.Property<string>("SignatureHash")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .HasColumnName("signatureHash")
                        .IsFixedLength()
                        .HasComment("Huella opcional del contenido que identifica el formato.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updatedAt")
                        .HasComment("Fecha y hora de la última actualización del registro.");

                    b.HasKey("Id");

                    b.HasIndex("ImportTemplateId");

                    b.HasIndex("SignatureHash")
                        .IsUnique()
                        .HasFilter("[signatureHash] IS NOT NULL");

                    b.ToTable("tbImportTemplatePatterns", null, t =>
                        {
                            t.HasComment("Patrones aprobados para detectar una plantilla de importación por contenido.");

                            t.HasCheckConstraint("CK_tbImportTemplatePatterns_definition", "[signatureHash] IS NOT NULL OR [requiredTermsJson] IS NOT NULL");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\";\",\"oficina\",\"fechamovimiento\",\"numerodocumento\",\"debito\",\"credito\",\"descripcion\"]"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AlternativeTermGroupsJson = "[[\"dollar amount\",\"dollars amount\"]]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\",\",\"name\",\"date\",\"minimum payment\",\"cash payment\",\"local amount\"]"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            AlternativeTermGroupsJson = "[[\"movimientos por rango de fechas\",\"movimientos de la cuenta\",\"movimientos del d\"]]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"banco de costa rica\"]"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            AlternativeTermGroupsJson = "[[\"descripcion\",\"detalle\"],[\"debito\",\"debitos\"],[\"credito\",\"creditos\"]]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"fecha\"]"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"consulta de financiamientos\",\"fecha\",\"concepto\",\"cuotas\",\"monto de cuota\",\"saldo inicial\",\"saldo faltante\"]"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"tarjeta de credito\",\"saldo en colones\",\"saldo en dolares\",\"fecha de pago de contado\"]"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"ver detalles del prestamo\",\"capital\",\"interes\",\"mora\",\"otros\",\"total\",\"saldo\"]"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"numero de tarjeta\",\"marca de tarjeta\",\"plan de lealtad\",\"pagos vencidos\",\"pago de contado\",\"fecha de corte\",\"total pago de contado\"]"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            ImportTemplateId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"banco nacional de costa rica\",\"estado de cuenta tarjetas de credito\",\"detalle de compras del periodo\",\"total pago de contado\"]"
                        });
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.BankAccount", b =>
                {
                    b.HasOne("Bancos.Mcp.Domain.Bank", "Bank")
                        .WithMany("Accounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.BankAccountImportTemplate", b =>
                {
                    b.HasOne("Bancos.Mcp.Domain.BankAccount", "BankAccount")
                        .WithMany("ImportTemplates")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bancos.Mcp.Domain.ImportTemplate", "ImportTemplate")
                        .WithMany("BankAccounts")
                        .HasForeignKey("ImportTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("ImportTemplate");
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.ExchangeRate", b =>
                {
                    b.HasOne("Bancos.Mcp.Domain.Bank", "Bank")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.ImportTemplatePattern", b =>
                {
                    b.HasOne("Bancos.Mcp.Domain.ImportTemplate", "ImportTemplate")
                        .WithMany("Patterns")
                        .HasForeignKey("ImportTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportTemplate");
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.Bank", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("ExchangeRates");
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.BankAccount", b =>
                {
                    b.Navigation("ImportTemplates");
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.ImportTemplate", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Patterns");
                });
#pragma warning restore 612, 618
        }
    }
}
