// <auto-generated />
using System;
using Bancos.Mcp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bancos.Mcp.Migrations
{
    [DbContext(typeof(McpCatalogDbContext))]
    partial class McpCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bancos.Mcp.Domain.ImportTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ContentKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ParserKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tbImportTemplates", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbImportTemplates_ContentKind", "[ContentKind] IN ('csv', 'html', 'xls', 'pdf')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "bcr-debit-csv-v1",
                            ContentKind = "csv",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Movimientos de cuenta BCR",
                            ParserKey = "bcr-debit-csv"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "bac-credit-csv-v1",
                            ContentKind = "csv",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Resumen de tarjeta BAC",
                            ParserKey = "bac-credit-csv"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "bcr-debit-html-xls-v1",
                            ContentKind = "html",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Movimientos BCR HTML",
                            ParserKey = "bcr-debit-html"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "bank-account-movements-xls-v1",
                            ContentKind = "xls",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Movimientos de cuenta XLS",
                            ParserKey = "bank-account-movements-xls"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "bac-credit-financing-xls-v1",
                            ContentKind = "xls",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Financiamientos BAC",
                            ParserKey = "bac-credit-financing-xls"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Code = "bac-credit-online-pdf-v1",
                            ContentKind = "pdf",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Tarjeta BAC en linea",
                            ParserKey = "bac-credit-online-pdf"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Code = "coopealianza-loan-pdf-v1",
                            ContentKind = "pdf",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Prestamo Coopealianza",
                            ParserKey = "coopealianza-loan-pdf"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Code = "bac-account-statement-pdf-v1",
                            ContentKind = "pdf",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Estado de cuenta consolidado BAC",
                            ParserKey = "bac-account-statement-pdf"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Code = "bn-card-statement-pdf-v1",
                            ContentKind = "pdf",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Estado de cuenta de tarjeta Banco Nacional",
                            ParserKey = "bn-card-statement-pdf"
                        });
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.ImportTemplatePattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativeTermGroupsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<short>("DetectorVersion")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PatternKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequiredTermsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureHash")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SignatureHash")
                        .IsUnique()
                        .HasFilter("[SignatureHash] IS NOT NULL");

                    b.HasIndex("TemplateId");

                    b.ToTable("tbImportTemplatePatterns", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbImportTemplatePatterns_Definition", "[SignatureHash] IS NOT NULL OR [RequiredTermsJson] IS NOT NULL");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\";\",\"oficina\",\"fechamovimiento\",\"numerodocumento\",\"debito\",\"credito\",\"descripcion\"]",
                            TemplateId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AlternativeTermGroupsJson = "[[\"dollar amount\",\"dollars amount\"]]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\",\",\"name\",\"date\",\"minimum payment\",\"cash payment\",\"local amount\"]",
                            TemplateId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            AlternativeTermGroupsJson = "[[\"movimientos por rango de fechas\",\"movimientos de la cuenta\",\"movimientos del d\"]]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"banco de costa rica\"]",
                            TemplateId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            AlternativeTermGroupsJson = "[[\"descripcion\",\"detalle\"],[\"debito\",\"debitos\"],[\"credito\",\"creditos\"]]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"fecha\"]",
                            TemplateId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"consulta de financiamientos\",\"fecha\",\"concepto\",\"cuotas\",\"monto de cuota\",\"saldo inicial\",\"saldo faltante\"]",
                            TemplateId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"tarjeta de credito\",\"saldo en colones\",\"saldo en dolares\",\"fecha de pago de contado\"]",
                            TemplateId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"ver detalles del prestamo\",\"capital\",\"interes\",\"mora\",\"otros\",\"total\",\"saldo\"]",
                            TemplateId = new Guid("10000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"numero de tarjeta\",\"marca de tarjeta\",\"plan de lealtad\",\"pagos vencidos\",\"pago de contado\",\"fecha de corte\",\"total pago de contado\"]",
                            TemplateId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            DetectorVersion = (short)1,
                            IsActive = true,
                            IsApproved = true,
                            PatternKind = "content-terms",
                            RequiredTermsJson = "[\"banco nacional de costa rica\",\"estado de cuenta tarjetas de credito\",\"detalle de compras del periodo\",\"total pago de contado\"]",
                            TemplateId = new Guid("10000000-0000-0000-0000-000000000009")
                        });
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.ImportTemplatePattern", b =>
                {
                    b.HasOne("Bancos.Mcp.Domain.ImportTemplate", "Template")
                        .WithMany("Patterns")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Bancos.Mcp.Domain.ImportTemplate", b =>
                {
                    b.Navigation("Patterns");
                });
#pragma warning restore 612, 618
        }
    }
}
